### PR TITLE
Close a security hole!

### PR DESCRIPTION
**Pull request by jacksonic**
https://commons.apache.org/proper/commons-collections/security-reports.html

### CODE REVIEW

**Comment by mic159** [comment]
Is this project dead?

**Comment by neophob** [comment]
feel free to submit a pr!

**Comment by mic159** [comment]
I do believe this is a PR?

**Comment by jacksonic** [comment]
It's just a version bump to avoid a security issue that was found there.
Use it or bump the version some other way at your discretion :D

**Comment by mic159** [comment]
When do you plan on doing the next release of PixelController?
I cant seem to get it to compile myself.

**Pull request merged**
